// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxtrrobtteylwgjqkjnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4dHJyb2J0dGV5bHdnanFram52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMTk5NjcsImV4cCI6MjA3MDU5NTk2N30.enyKoOXMWouu_O54ZLvvb5mLBGPfVole9retsIIeiR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});